### ISSUE TITLE
front-end

### ISSUE THREAD

**Issue by sanchitachaurasia** [ThatSINEWAVE/OSINT-Toolkit#2]
**The header is not fixed, but footer is.**
This just seems a bit odd to me. I would like to redesign the webpage so that it looks neater and more web-maintained.

**Comment by ThatSINEWAVE** [comment]
Sure, feel free to add your contributions!

**Comment by ThatSINEWAVE** [comment]
(I commented this on the PR but ill post it here too)
Looks great! Turned out better that i could've ever done it myself, love the design on the FAQ page!
Let me know when you get to the rest of the pages so i can merge the project and credit you in the README. 
You can join the Discord server i got in the README and we can discuss more there.
